test: &default

  # Credentials for REST APIs
  client_id: AdymMAmFj_R3H21IsLNq2Ou1PqIUMhI5XGRyXVxPCVyf05Xjo__2EDM3v6rsDVnrh2DaJE9bJVr0bCMP
  client_secret: EDyJwIuh1BpIoQaDwYYtwf7FmDqvhRKySVyj5TMAjGKgt25E006Ekz3XPvrkuJMPyPswewcBQvy_jdtM

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: danielmonteropereira@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
